#!/usr/local/bin/bash

echo "0---------------------------------------------------------------------------0"
echo "| add superuser LDWG                                                        |"
echo "| - copy /usr/bin to /tmp/usr and nullfs-mount /tmp/usr/bin on /usr/bin     |"
echo "|   (required to change the setuid of /usr/bin/su to enable the su command) |"
echo "| - set password to LDWG                                                    |"
echo "| - set home dir to /usr/local/home/LDWG                                    |"
echo "0---------------------------------------------------------------------------0"

cp -R /usr/bin /tmp/usr
mount_nullfs /tmp/usr/bin /usr/bin
chmod 4555 /usr/bin/su
pw useradd LDWG
mkdir -p /usr/local/home/LDWG
echo "LDWG" | pw usermod LDWG -h 0 -d /usr/local/home/LDWG -g wheel


